spring:
  application:
    name: "api-tattoo"
  security:
    user:
      name: user
      password: 123456
  datasource:
    url: jdbc:h2:mem:tattoo
    username: tattooADM
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false